### ISSUE TITLE
knnLookup: k > size of source data leads to segfault

### ISSUE THREAD

**Issue by colinsheppard** [gmbecker/SearchTrees#1]
If a user creates a tree with a data frame with N rows but then sets k equal to a value greater than N, it leads to a segfault and the entire R session crashes. This issue can be difficult to debug and disruptive to user workflows.

Instead, can you please add a simple check for this condition and fail with an error message (i.e. use "stop")?

To reproduce:

```
library(SearchTrees)
tree <- createTree(data.frame(x=1:10,y=10:1))
knnLookup(tree, 5.5, 6.25,k=1) # works
knnLookup(tree, 5.5, 6.25,k=10) # works
knnLookup(tree, 5.5, 6.25,k=11) #fails
```

![image](https://user-images.githubusercontent.com/333206/223287921-c550ac60-1b4e-448e-affb-559e19c5ede5.png)

**Comment by gmbecker** [comment]
Hi @colinsheppard 

Thanks for the report. I haven't looked at this code in ages, but it looks like an easy fix as you suggest.

**Comment by gmbecker** [comment]
@colinsheppard the above commit fixes this issue. I'm not sure when it will get onto CRAN, but I'll try to get it there at some point.

```
> library(SearchTrees)
> tree <- createTree(data.frame(x=1:10,y=10:1))
> knnLookup(tree, 5.5, 6.25,k=1) # works

     [,1]
[1,]    5
> knnLookup(tree, 5.5, 6.25,k=10) # works

     [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
[1,]    5    6    4    7    3    8    2    9    1    10
> knnLookup(tree, 5.5, 6.25,k=11) #fails

Error in knnLookup(tree, 5.5, 6.25, k = 11) : 
  got k (11) larger than total number of observations encoded in the tree (10)
> sessionInfo()
R version 4.2.2 (2022-10-31)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur ... 10.16

Matrix products: default
BLAS:   /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRblas.0.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] SearchTrees_0.5.6

loaded via a namespace (and not attached):
[1] compiler_4.2.2
```

**Comment by colinsheppard** [comment]
Wow, thank you for the quick patch! 

I use this package all of the time and find it very valuable, your work is much appreciated.
